#! /usr/bin/env python

from pkg_resources import resource_filename

import pyramid.scripts.pserve


def main():
    config = resource_filename("weboot.utils", "default_conf.ini")
    print "Using configuration at ", config
    args = ["--reload", config]
    return pyramid.scripts.pserve.main(args)

if __name__ == '__main__':
    raise SystemExit(main())
